apiVersion: v1
kind: Secret
metadata:
  name: python-app-secrets
type: Opaque
stringData:
  DB_USER: {{ required "secrets.dbUser is required" .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ required "secrets.dbPassword is required" .Values.secrets.dbPassword | quote }}

